[client]
showErrorDetails = true
showWarningOnDirectExecution = false

[logger]
level = "info"

[theme]
base = "dark"
primaryColor = "#FF6B6B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#161B22"
textColor = "#FFFFFF"
font = "sans serif"

